import type { ConsoleId } from '@emulators/core-interface';

/**
 * One console's MD5 -> canonical-name table, generated by
 * `scripts/build-cover-index.mjs` and bundled per app. Apps hand these to
 * `AppConfig.coverIndexes`; nothing here reaches the network.
 */
export interface CoverIndex {
  console: ConsoleId;
  /** Packed `"<md5 prefix> <name>"` lines — see the generator for the format. */
  source: string;
}

/** Must match KEY_LENGTH in scripts/build-cover-index.mjs. */
const KEY_LENGTH = 12;

interface ParsedIndex {
  byMd5: Map<string, string>;
  /** Ambiguous keys are absent by design — see `parse`. */
  byName: Map<string, string>;
}

// Keyed by the index object itself, which each app builds once at module
// scope. Weak so a hot reload doesn't pin the old table.
const parsed = new WeakMap<CoverIndex, ParsedIndex>();

/**
 * Strips everything that distinguishes dumps of the same game — region tags,
 * revisions, punctuation — so a user's filename has a chance of matching.
 * "Pokemon - Emerald Version (USA, Europe)" -> "pokemonemeraldversion".
 */
export function normalizeTitle(title: string): string {
  return title
    .toLowerCase()
    .replace(/\([^)]*\)/g, '')
    .replace(/\[[^\]]*\]/g, '')
    .replace(/^the\s+/, '')
    .replace(/[^a-z0-9]/g, '');
}

function parse(index: CoverIndex): ParsedIndex {
  const cached = parsed.get(index);
  if (cached) return cached;

  const byMd5 = new Map<string, string>();
  const byName = new Map<string, string>();
  // Names that normalized to a key already taken by a *different* name. They
  // are dropped rather than resolved, because there is no principled way to
  // choose between "Pokemon - Red Version (USA, Europe)" and the (Japan)
  // dump — and picking one arbitrarily is how the wrong box art ends up on a
  // game. Exact MD5 matching is what covers those; this map is only a
  // fallback for ROMs whose hash is not in the table at all.
  const ambiguous = new Set<string>();

  for (const line of index.source.split('\n')) {
    if (line.length <= KEY_LENGTH + 1) continue;
    const key = line.slice(0, KEY_LENGTH);
    const name = line.slice(KEY_LENGTH + 1);
    byMd5.set(key, name);

    const normalized = normalizeTitle(name);
    if (!normalized || ambiguous.has(normalized)) continue;
    const existing = byName.get(normalized);
    if (existing === undefined) {
      byName.set(normalized, name);
    } else if (existing !== name) {
      byName.delete(normalized);
      ambiguous.add(normalized);
    }
  }

  const result = { byMd5, byName };
  parsed.set(index, result);
  return result;
}

/** `md5` is the full lower-case hash as stored in `roms.content_md5`. */
export function lookupByMd5(index: CoverIndex, md5: string): string | null {
  return parse(index).byMd5.get(md5.toLowerCase().slice(0, KEY_LENGTH)) ?? null;
}

/** Takes an already-normalized title, so callers normalize once for N indexes. */
export function lookupByNormalizedTitle(index: CoverIndex, normalized: string): string | null {
  return parse(index).byName.get(normalized) ?? null;
}
